"""additional fields for post

Revision ID: 137f3adad7c7
Revises: bc657a0f21c0
Create Date: 2026-01-14 19:13:59.014017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '137f3adad7c7'
down_revision: Union[str, Sequence[str], None] = 'bc657a0f21c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('post', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('post', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('post', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'deleted_at')
    op.drop_column('post', 'deleted')
    op.drop_column('post', 'updated_at')
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
