"""additional updated field for post

Revision ID: 25e277b3fca7
Revises: 137f3adad7c7
Create Date: 2026-01-14 19:15:21.715278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25e277b3fca7'
down_revision: Union[str, Sequence[str], None] = '137f3adad7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'updated')
    # ### end Alembic commands ###
